# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Update Rules

on:
  push:
    branches:
    - main
    paths:
    - rules.txt

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
        env:
          rulesChannel: ${{ secrets.rulesChannel }}
          token: ${{ secrets.token }}
          rulesWebhook: ${{ secrets.rulesWebhook }}
          announcementWebhook: ${{ secrets.announcementWebhook }}
      - run: npm ci
      - run: node index.js
