name: Update Rules

on:
  pull_request:
    branches:
    - main
    paths:
    - rules.template.txt

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .scripts
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run update
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'rules.txt'
          message: 'Updated rules.txt'
          default_author: github_actions
